web-vision/deepltranslate-core

README.md
ext_emconf.php

Extension description changes.

[TASK] Extension description changes.

---

composer.json

Use "GPL-2.0-or-later" because  "GPL-2.0+" is deprecated.
Resolves: #17

[TASK] Fix license in composer.json

---

Classes/Domain/Model/Settings.php

Closes: #93
Needed as long there is support for TYPO3 v9 LTS. With v10 the doc blocks are not needed anymore.

Add php doc blocks

---

Classes/Hooks/DataHandlerHook.php

Due to a bug in the DataHandlerHook, the glossary entries were not synchronized to the table tx_wvdeepltranslate_domain_model_glossariessync.
This typically occurred in sites with several languages because a for loop was exited too early.
Due to the glossary entries not being synchronized, the glossary was not used for translation.
Resolves: #99

[BUGFIX] Fix glossary sync persistance

---

Classes/Hooks/DataHandlerHook.php

Problem occurs with PHP 8.1.
Resolves: #98

[BUGFIX] Fix undefined array key in DataHandlerHook

---

Classes/Service/DeeplService.php
Configuration/Services.yaml
Tests/Functional/Fixtures/ExtensionConfig.php
Tests/Functional/Services/DeeplServiceTest.php
ext_localconf.php

Fixes #63.
This PR will add support to automatically check for available DeepL supported languages. For not running into API restrictions a caching is added.

[FEATURE] add supported languages automatically from API

---

Classes/Hooks/TranslateHook.php

[BUGFIX] Prevent TypeError by adding string cast before explode()

---

Classes/Override/DeeplRecordListController.php
Classes/Override/v10/DatabaseRecordList.php
Classes/Override/v10/DeeplPageLayoutView.php
Classes/Override/v10/DeeplRecordListController.php
Resources/Private/Backend/Partials/PageLayout/LanguageColumns.html
Resources/Private/Backend/Partials/v10/PageLayout/LanguageColumns.html
ext_typoscript_setup.txt

- PHP error had to be fixed in an override class.
- The new translation button was only render with the last language version, this is now fixed. There should now be a DeepL translation button in Record Listener for all languages.
- In addition, the language translation selects in Records List and Pages View modules were incorrect in different versions and had to be adjusted.

Fix language translate button and select

---

Classes/Hooks/AllowLanguageSynchronizationHook.php
ext_localconf.php

Separate Bugfix from #140 
Add DeepL Translation for fields with "behaviour->allowLanguageSynchronization" enabled, sets synchronization to custom
Fixes #87 
Fixes #115

 Fix DeepL Translation for fields with behaviour->allowLanguageSynchronization

---

Classes/Override/DatabaseRecordList.php

Allows Pages translation button, even if parent not translated.
This is default behaviour for pages records, so we have to respect, too.

[BUGFIX] v11: Allow pages always getting localized in RecordList

---

composer.json

tx_news comes with allowLanguageSynchronisation behavior for some fields. According to this, this ext should be used as dev requirement for testing the l10n_state and the behaviour with state modes.

[TASK] add news extension as dev-require

---

Classes/Hooks/AllowLanguageSynchronizationHook.php
Classes/Override/DatabaseRecordList.php
Classes/Override/DeeplRecordListController.php
Classes/Override/v10/DatabaseRecordList.php
Classes/Override/v10/DeeplPageLayoutView.php
Classes/Override/v10/DeeplRecordListController.php
Classes/Utility/DeeplBackendUtility.php
Classes/ViewHelpers/DeeplTranslateViewHelper.php
Resources/Private/Backend/Partials/PageLayout/LanguageColumns.html
Resources/Private/Backend/v10/Partials/PageLayout/LanguageColumns.html
ext_typoscript_setup.txt

All DeepL related localization elements are hidden, if target language is not supported by DeepL.
Does not appear to the Localization wizard. Fixes only translation buttons and translation dropdowns.
fixes #30

[BUGFIX] Hide DeepL controls for not supported languages

---

ext_conf_template.txt

Because a string false becomes true with a type-hint on bool, the backend module was displayed further in v11. Therefore, the config now uses string int so that these can be type-hinted.

[BUGFIX] Fix active old backend module condition type handling

---

ext_emconf.php

EXT: wv_deepltranslate requires at least PHP 7.4, as stated in its `composer.json` file. However, if the TYPO3 instance is a non-Composer-based installation, the extension will be installed regardless of the used PHP version, leading to hard crashes.
To catch this case, the PHP version constraint is added to `ext_emconf.php`.
Fixes: #170

[BUGFIX] Require PHP version in ext_emconf.php

---

composer.json
ext_emconf.php

fixes #151 
* Affected TYPO3 version: 11 and above
* installed ext: https://github.com/studiomitte/recordlist_thumbnail
This is because recordlist_thumbnail x-classes the DatabaseRecordList, as we do, too. 
https://github.com/studiomitte/recordlist_thumbnail/tree/main/Classes/Xclass
It would a big impact, overriding the Xlcass in this extension, because we can't consider side effects.
Solution: Add conflict to recordlist_thumbnail

Add conflicts to recordlist_thumbnail

---

Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml
Classes/Hooks/TranslateHook.php
ext_emconf.php

This change adjusts `Build/Scripts/runTests.sh` and
`Build/testing-docker/docker-compose.yml` to add a
docker image prefix. This prefix is hardcoded to use
the TYPO3 core-testing images from the TYPO3 GitHub
Container Registry by setting the prefix to `ghcr.io`.
DeepL Mock Api image is raised to use `latest` tag.
Functional container scripts are extended with a
deeplmockapiserver start check.
See: https://github.com/orgs/TYPO3/packages

[TASK] Use `core-testing-*` images from `ghcr.io`

---

Classes/Service/Client/Client.php

I have glossary with ~4900 entries. When trying to submit it to DeepL, I received an exception:
I could solve it, by moving the body content from the Request to the options.
For any reason, guzzle's `PrepareBodyMiddleware` was not able to calculate the correct content length for your way.

[BUGFIX] Use correct POST body for submitting the glossary

---

Classes/Service/DeeplGlossaryService.php

If one glossary UUID is outdated for any reason, the complete sync fails with an exception.
This PR replaces catches the exception and adds a flash message instead. So the further processing still will happen and the new glossary (or even multiple glossaries) can be updated/recreated correctly.

[TASK] Make glossary sync more tolerant of outdated IDs

---

Classes/Hooks/TranslateHook.php

The jSON response comes with encoded HTML characters. Redecode the chars
Closes #86

[BUGFIX] decode html special characters

---

Classes/Service/DeeplService.php

PHP Runtime Deprecation Notice: Creation of dynamic property WebVision\WvDeepltranslate\Service\DeeplService::$client is deprecated in wv_deepltranslate/Classes/Service/DeeplService.php line 50

[BUGFIX] Fix runtime deprecation notice

---

Classes/Upgrades/GlossaryUpgradeWizard.php
Tests/Functional/Updates/Fixtures/Extension/test_extension/ext_tables.sql
Tests/Functional/Updates/Fixtures/TableToMigrate.xml

Fields like startime and endtime are no longer used in glossary entry tables and can be ignored by the update script.
Close #208

[BUGFIX] Exclude fields in upgrade wizards

---

Classes/Client.php
Tests/Functional/ClientTest.php

Glossary entries synchronized wrong value.
Closes #209

[BUGFIX] Glossary entries

---

Classes/Utility/DeeplBackendUtility.php

Due to coding issues the initial was set wrong. This bugfix resolves the issue
Closes #217

[BUGFIX] Glossary is not used

---

Classes/Upgrades/GlossaryUpgradeWizard.php

Using the `rowCount(` method for an `SELECT` query
is not reliable. That's already documented in the
TYPO3 documentation. It's recommended to use a `COUNT()`
query instead.
See: https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/Database/Statement/Index.html#rowcount
This change uses now a `COUNT(*)` based  query to avoid
the unreliable `rowCount()` method in the corresponding
`WebVision\WvDeepltranslate\Upgrades\GlossaryUpgradeWizard`.
This will be fixed in main within other stuffs and this
is only the manual backport for the 3.x branch.
Releases: 3.x

[TASK] Avoid `rowCount()` for select query

---

Classes/Domain/Repository/GlossaryRepository.php
Resources/Private/Backend/Partials/PageLayout/LanguageColumns.html

If no glossary is given, the TranslateHook crashes because of wrong return param. This fix corrects the return value to an empty array.
Additionally, the label for translation dropdown is removed due to backend UI limitations.

Fix Problem with translation no glossary given

---

.ddev/commands/web/run-tests
Build/Scripts/composer-for-core-version.sh
Build/Scripts/runTests.sh
Build/phpunit/FunctionalTests-10.xml
Build/phpunit/UnitTests-10.xml
Build/testing-docker/docker-compose.yml
composer.json

This change adds basic support to test against
TYPO3 v12 core. That includes adding corresponding
switches to `Build/Scripts/runTests.sh` and the
ddev `runtests.sh` script.
TYPO3 v12 testing will be done with PHPUnit v10
only, therefore we add corresponding configuration
files aside of the PHPUnit v9 config files.
**Note:** TYPO3 v12 tests are left out per intention
for now, because they would not be green
yet.
```shell
composer require --dev --no-update \
"b13/container":"^2.2.2" \
"helmich/typo3-typoscript-lint":"^3.1.0" \
"helmich/phpunit-json-assert":"^3.4.3 || ^3.5.1"
```
Resolves: #242

[TASK] Add TYPO3 v12 support to Build/Scripts/runTests.sh

---

Classes/Controller/Backend/AjaxController.php
Classes/Override/LocalizationController.php
Configuration/Backend/AjaxRoutes.php
Configuration/Icons.php
Resources/Public/JavaScript/Localization.js

A new Ajax function does not belong in an XClass/Override. It does not belong there thematically.

[TASK] Move ajax extension config check in own class

---

ext_typoscript_setup.txt

There are no extbase based domain models and
repository left. Removing the related extbase
persistance configuration have been missed.
This change now removes the obsolete configuration
as part of code cleanup and streamlining.
Resolves: #193

[TASK] Remove extbase persistence mapping

---

Classes/Hooks/AllowLanguageSynchronizationHook.php

> PHP Warning: Undefined array key "l10n_mode" in wv_deepltranslate/Classes/Hooks/AllowLanguageSynchronizationHook.php line 34
Releases: main, 3.x

[BUGFIX] Avoid undefined array key warning in `AllowLanguageSynchronizationHook`

---

Classes/Override/LocalizationController.php

> Core: Exception handler (WEB: BE): TYPO3\CMS\Core\Error\Exception, code #1476107295, file /private/typo3/sysext/core/Classes/Error/ErrorHandler.php, line 137: PHP Warning: Undefined array key "mode" in /private/typo3conf/ext/wv_deepltranslate/Classes/Override/LocalizationController.php line 77- Exception: PHP Warning: Undefined array key "mode" in /private/typo3conf/ext/wv_deepltranslate/Classes/Override/LocalizationController.php line 77, in file /private/typo3/sysext/core/Classes/Error/ErrorHandler.php:137

[BUGFIX] Avoid undefined array key warning in `LocalizationController`

---

Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml
docker-compose.yaml

Having multiple execution points are not really
user friendly. Distributing config and docker
compose files is also not a really good idea.
This change now integrates the documentation
rendering container as `runTests.sh` task and
into the underlying `docker-compose.yaml`.
Furthermore, the `develop` tag is used as this
is the real latest rendering container provided
by the TYPO3 documentation team. This may change
at any point and can than be changed back. With
this, rendering warnings are solved due a bug
in the published `latest` container.
Thus removing the file in the project root
folder to clean that up a bit.
Resolves: https://github.com/web-vision/wv_deepltranslate/issues/256
Releases: main

[TASK] Migrate documentation rendering to `runTests.sh`

---

Tests/Functional/ClientTest.php
Tests/Functional/ConfigurationTest.php
Tests/Functional/Form/Items/SiteConfigSupportedLanguageItemsProcFuncTest.php
Tests/Functional/Hooks/TranslateHookTest.php
Tests/Functional/Services/DeeplServiceTest.php
Tests/Functional/Services/LanguageServiceTest.php
Tests/Functional/Updates/GlossaryUpgradeWizardTest.php

It's recommend that test classes should not
extend from each other. This is not the case,
so mark all tests final.
Releases: main

[TASK] Mark test classes `final`

---

Configuration/TCA/Overrides/pages.php
Configuration/TCA/Overrides/tt_content.php
ext_localconf.php
ext_tables.php

The `TYPO3_MODE` constant defined is deprecated
and removed with TYPO3 v12. It's recommended to
use the `TYPO3` constant for the known file
`defined() or die()` guard.
This change replaces the simply guards with the
new constant, which is already available in the
TYPO3 v11 version.
**NOTE:**   One usage in `ext_localconf.php` is
not touched as this requires a more
enhanced replacement. That has been
provided with #258 already.
Resolves: #259
Related: #128
Related: https://review.typo3.org/c/Packages/TYPO3.CMS/+/66948
Releases: main

[TASK] Replace deprecated `TYPO3_MODE` constant usage

---

Classes/Hooks/PageRendererHook.php
ext_localconf.php

Registering custom backend javascript modules have been
done historically by instantiating the PageRenderer in
the `ext_localconf.php` for `TYPO3_MODE === 'BE'`. That
was a valid way to do so.
The `TYPO3_MODE` constant has been deprecated and will
be removed in TYPO3 v12, which means that adding the
JS module could not be restricted to the backend context.
Furthermore, instantiating the PageRenderer with TYPO3
v12 in the `ext_localconf.php` file would emit an error
exception due to the fact that the page renderer needs
a cache. Instantiating the CacheManager in an early stage
is not possible which further disqualifies to add the
JavaScript module in the `ext_localconf.php`.
Generally there are multiple ways to mitigate this issue,
but the decision has been made to use an `PageRenderer` …

[TASK] Avoid instantiating PageRenderer in `ext_localconf.php`

---

Classes/Controller/GlossarySyncController.php
Classes/Controller/SettingsController.php
Classes/Hooks/ButtonBarHook.php
Classes/Hooks/Glossary/UpdatedGlossaryEntryTermHook.php
Classes/Override/DeeplRecordListController.php
Classes/Utility/DeeplBackendUtility.php

The `LocalizationUtility::translate()` is used
in several places to translate something. The
method may return a string or null, where as
the used places usual expects to have a valid
string afterwards. For example, if the return
value is null and used to pass it to another
method like `htmlspecialchars()` this will
violates added argument types with PHP 8.0.
To avoid emitted PHP warnings call to this
method is guarded with a explicit `(string)`
type cast to mitigate this issue.
Releases: main, 3.0

[BUGFIX] Guard `LocalizationUtility::translate` with `(string)` cast

---

Configuration/SiteConfiguration/Overrides/sites.php

The siteconfiguration related tca override contained a
version switch to add the custom extension field only
for TYPO3 v11 and up.
Beside it should considered to drop that custom field,
the version check is removed because it is guaranteed
by the composer TYPO3 version constraint of the main
branch.
Releases: main

[TASK] Remove obsolete version check from siteconfiguration tca

---

Build/phpstan/phpstan-baseline.neon
Classes/Domain/Repository/GlossaryEntryRepository.php
Classes/Domain/Repository/GlossaryRepository.php
Classes/Domain/Repository/PageRepository.php
Classes/Override/LocalizationController.php
Classes/Utility/DeeplBackendUtility.php

This change streamlines the code base to
a modern usage of doctrine/dbal to avoid
deprecated methods and constructs.
Some `@todo` comments have been added to
document future improvements and stuff
which should be considered or solved.
Tasks:
------
* Use `fetchAssociative()` instead of `fetch()`.
* Use `fetchAllAssociative()` instead of `fetchAll()`.
* Use `and()` instead of `andX()`.
* Use `or()` instead of `orX()`.
* Use `executeQuery()` for queries returning a result
set, e.g. SELECT and COUNT queries.
* Use `executeStatement()` for quereis returning a
affected row number, e.g. INSERT, UPDATE and DELETE
queries.
* Use placeholder to ensure proper dbms value quoting
even for static values.
**NOTE:** Entries have been added to the phpstan
baseline. Argument and return type array
shapes …

[TASK] Streamline doctrine/dbal usages

---

Build/Scripts/composer-for-core-version.sh

For adding basic TYPO3 v12 core testing support
some commands have been copied. Sadly, not the
correct versions have been used for the output.
That means, it does not matches what is installed.
This change now fixes this to have the echo test
aligned to what is done. That avoids confusion.
Releases: main

[TASK] Display correct versions in core switch script

---

Classes/Hooks/DeeplPreviewFlagGeneratePageHook.php

[BUGFIX] Determine correct Preview mode in TYPO3 v9

---

Classes/Utility/DeeplBackendUtility.php

Until TYPO3 v10, the page ID in requests is given as `pageId` instead of
`id`. This bugfix respects the given request and detects correct page ID
in DeeplBackendUtility for determining glossary.
Backport to v4 not necessary, as since TYPO3 v11 the ID is given as `id`
closes #238

[BUGFIX] Determine glossary correct on current page

---

Classes/Override/LocalizationController.php

`b13/container` moved a class with v2.1.0 to another
namespace. We instantiated and called that class to
re-run code in xclassed class which both extensions
needs to xclass and combine both tasks.
This change now checks for both possible classes and
use the correct ones. Using kind of package or composer
information is not reliable enough and more complex
than the chosen `class_exist` check.
The newer namespace is checked first, in case the
container extensions adds a class_alias for the old
one. Directly using the new class if existing is the
better way.
See: https://github.com/b13/container/commit/5d57961165efd2828fafcf291c5e19b1400baef1#diff-1b5dddc7fdc72ce709fe89a91a8873332a6f6755209043cb81c3b116ee70f738
Resolves: #276

[BUGFIX] Respect correct namespace for used `b13/container` class

---

Classes/Hooks/TranslateHook.php

GoogleTranslateService::translate() expects the source language as first parameter and the target language as second parameter. So far, the target language was passed in both cases. This led to the error "Bad language pair". This fix sets the source language as first parameter instead.

[BUGFIX] Fix google translation error "Bad language pair"

---

Documentation/Editor/Usage/Index.rst

Just a small hint in the docs about the table configuration. Just in case an editors wonders, why translation doesn't work for certain TCA fields.

[DOCS] Add note about table configuration for custom records

---

composer.json

This tweaks the order in which extensions are being loaded. To let EXT:wv_deepltranslate have the upper hand when it comes to xclassing LocalizationController it's necessary to define `b13/container` as a kinda "dependency" of this extension.
Without it this happens:

[BUGFIX] LocalizationController not loaded when EXT:container is installed

---

ext_tables.php

See https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ApiOverview/Localization/ManagingTranslations.html?highlight=locallangxmloverride
This fixes the "undefined" labels situation in TYPO3 11:

[BUGFIX] Fix locallangXMLOverride

---

Classes/Upgrades/GlossaryUpgradeWizard.php

Avoid SQL errors in the Upgrade Wizard from v2 to v3. Errors like:
```
In AbstractMySQLDriver.php line 79:
An exception occurred while executing 'INSERT INTO `tx_wvdeepltranslate_glossaryentry` (`uid`, `pid`, `tstamp`, `crdate`, `cruser_id`, `de  
leted`, `hidden`, `sorting`, `sys_language_uid`, `l10n_parent`, `l10n_source`, `l10n_state`, `l10n_diffsource`, `t3ver_oid`, `t3ver_wsid`,  
`t3ver_state`, `t3ver_stage`, `t3ver_count`, `t3ver_tstamp`, `t3ver_move_id`, `term`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?  
, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,   
?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, …
```

Fix upgrade wizard

---

Classes/AbstractClient.php

When converting the client, the proxy configuration via TYPO3 was no longer taken into account. This will be made up for with this change.
resolve #330

[BUGFIX] Use TYPO3 configured proxy for deepl client

---

Build/phpstan/Core11/phpstan-baseline.neon
Build/phpstan/Core12/phpstan-baseline.neon
Classes/Domain/Repository/GlossaryRepository.php

Based on the concept the matching glossaries for the current site root tree should be used for translation process. Glossaries are managed on default pages with the `glossaries` module attached, thus are free to be defined within the page tree structure. Using a page traversal approach from the detected site root becomes really costly as it traverse the full page tree beneath the matched site root, thus becoming quickly quite costly.
Albeit not the best approach, retrieving pages with the module attached and using the SiteFinder and therefore the rootline to sort out module pages not included for the site root reduces the traversed and retrieved pages white a lot.
Note: With dropping TYPO3 v12 support it would be possible to use handcrafted common table expressions to further optimize …

[BUGFIX] Mitigate unrelated page traversal for glossary lookup

---

Classes/AbstractClient.php

With #331 the TYPO3 proxy setting has been validated
and set as `DeepL Guzzle Client` transport option to
have a proper configured proxy used.
The TYPO3 proxy setting however allows setting it as a
single string url or as array for different protocols,
which is not respected.
This change modifies the `AbstractClient->getTranslator()`
implementation to handle this double structure for named
option correctly now.
[1] https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Configuration/Typo3ConfVars/HTTP.html#typo3ConfVars_http_proxy
Related: #331

[BUGFIX] Ensure full compatible for proxy setting to retrieve Translator 

---

ext_tables.php

The locallang overrides in ext_localconf.php were only required for older versions of TYPO3. Now we can remove this configuration

[TASK] Remove locallang overrides and tca description registry

---

Tests/Functional/Fixtures/Traits/SiteBasedTestTrait.php

With PHP 8.4 marking method parameter implicitly nullable
is deprecated and will emit a `E_DEPRECATED` warning. One
recommended way to resolve this, is making it explicitly
nullable using the `?` nullable operator or adding a null
type to an union type definition. [[1]](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated)
This prepares the way towards PHP 8.4 compatibility.
* [[1] https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated)
Resolves: #344

[TASK] Avoid implicitly nullable class method parameter

---

composer.json

With this commit the version usage of the deeplcom/deepl-php package should become stricter, so that our tests do not fail unexpectedly.

Set the deepl-php requirement strict

---

Configuration/Services.php
composer.json

Ensure the DeepL translate usage widget is registered only if the 'dashboard' extension is loaded. This prevents errors in environments where the 'dashboard' extension is not available by execute the cache flush action.
Resolve #360

Conditionally add dashboard widget

---

.ddev/docker-compose.deeplmockserver.yml
.github/workflows/testcore11.yml
.github/workflows/testcore12.yml
Build/Scripts/runTests.sh

> Note that https://github.com/DeepLcom/deepl-mock needs to create a release for the latest tag
> See: https://github.com/DeepLcom/deepl-mock/issues/5
- **[TASK] Switch deeplmockapi server image to `ghcr.io/web-vision/wv-deeplmockapi-server`**
The used container image for the `DeepL Mock API Server` has
been outdated. Instead of creating manual build again this
has now been properly solved by creating a public repository
for the container image build along with automatic update
rebuild and tagging. [1][2]
This change now uses the new image instead of the stalled one.
[1] https://github.com/web-vision/wv-deeplmockapi-server
[2] https://github.com/web-vision/wv-deeplmockapi-server/pkgs/container/wv-deeplmockapi-server
- **[TASK] Remove upper version constraint for `deeplcom/deepl-php`**
Due …

[TASK] Replace `DeepL Mock Api Server` container image

---

Classes/Event/Listener/UsageToolBarEventListener.php
Classes/Hooks/UsageProcessAfterFinishHook.php
Classes/Service/UsageService.php
Configuration/Services.php
Resources/Private/Backend/Templates/Widget/UsageWidget.html
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Public/Icons/actions-localize-deepl.svg

Based on formating styles in PR #357 and the desire for a threshold in issue #343 I have
tweaked the severity level determination in all usage bars (flashmessage, system infobox, widget).
Based on warning levels in other software (90%, 98%, 100%) each info box will use a different 
severity color according to the currently used quota.
The widget is a bit more compact now, since it used a lot of whitespace before,
which makes the dashboard unnecessary large.

Usage treshold & severity levels

---

Classes/Hooks/ButtonBarHook.php

[BUGFIX] Return buttons if page is not callable

---

Build/phpstan/Core11/phpstan-baseline.neon
Build/phpstan/Core12/phpstan-baseline.neon
Classes/Domain/Repository/GlossaryRepository.php
Classes/Hooks/AbstractTranslateHook.php
Classes/Hooks/TranslateHook.php
Classes/Service/DeeplService.php
Classes/Service/ProcessingInstruction.php
Classes/Utility/DeeplBackendUtility.php
Configuration/Services.php
Tests/Functional/Hooks/TranslateHookTest.php
Tests/Functional/Regression/Fixtures/Results/translateWithGlossary.csv
Tests/Functional/Regression/Fixtures/glossary.csv
Tests/Functional/Regression/GlossaryRegressionTest.php
Tests/Functional/Services/DeeplServiceTest.php
Tests/Functional/Services/UsageServiceTest.php

The DeeplBackendUtility tried to detect the current working page by guessing the page id via the global request. In some cases no request is given, like on CLI calls. Avoiding errors not using the glossary when not calling translation via backend, a new service `ProcessingInstruction` is added, saving the current instructions inside the global runtime cache. This information can now get detected in every point of the translation and allows a correct detection of the current working page including a valid glossary, if one exists.
A regression test is added demonstrating the glossary is now detected and respected, even if no request is set up.

[BUGFIX] Working with glossary without a request not possible

---

.github/workflows/testcore12.yml
Tests/Functional/AbstractDeepLTestCase.php
Tests/Functional/ClientTest.php
Tests/Functional/Services/DeeplServiceTest.php
Tests/Functional/Services/UsageServiceTest.php

This change adds the dry-run flag (`-n`) to the php-cs-fixer
code-quality execution within the Github Action workflow file
to emit an non-zero exit code when changes are detected to
ensure failing job-run in this case.
Second commit applies php-cs-fixer to get the pipeline green,
which validates that it works again.

[TASK] Ensure failing `php-cs-fixer` within Github Action pipeline

---

.github/workflows/testcore11.yml
.github/workflows/testcore12.yml
Tests/Functional/Regression/GlossaryRegressionTest.php

- **[TASK] Ensure failing `php-cs-fixer` within Github Action pipeline**
This change adds the dry-run flag (`-n`) to the php-cs-fixer
code-quality execution within the Github Action workflow file
to emit an non-zero exit code when changes are detected to
ensure failing job-run in this case.
Backport of 1b9b3c324b30f090fa4cf044fddb387c47ff272f  of merged #384.
- **[TASK] Apply php-cs-fixer changes**
This change applies `php-cs-fixer` modifications which
slipped into the code-base because the corresponding
code-quality check missed the dry-run flag and doesn't
fail when changes has been detected.
Backport of #384.

[TASK] Ensure failing php-cs-fixer within Github Action pipeline (backport #384)

---

Tests/Unit/Access/AllowedGlossarySyncAccessTest.php
Tests/Unit/Access/AllowedTranslateAccessTest.php

Next `typo3/testing-framework` version `8.x`
includes additional integrity checks within
the provided abstract test cases.
That requires that `setUp()` and `tearDown()` calls
needs to hit the parent methods. Some tests overrides
the `setUp()` method in tests but fail to call the
parent method.
This change adds the missing `parent::setUp()` calls to
prepare towards upgrading `typo3/testing-framework`.

[TASK] Ensure `TestCase::setUp()` parent call chain in tests

---

Tests/Functional/AbstractDeepLTestCase.php
Tests/Functional/Hooks/ButtonBarHookTest.php
Tests/Functional/ViewHelpers/ExtensionActiveViewHelperTest.php

The next `typo3/testing-framework` includes additional
extension dependency check and sorting and will fail to
execute tests when not all extensions are configured as
`$testExtensionToLoad` or `$coreExtensionsToLoad` within
the functional test.
This change adds the missing extension configuration to
functional test cases to prepare the way for the next
`typo3/testing-framework` version and adding TYPO3 v13
suppport.

[TASK] Ensure to define all depending extension in functional tests

---

Build/phpstan/Core12/phpstan-baseline.neon
Tests/Functional/Fixtures/Traits/SiteBasedTestTrait.php
composer.json

- **[TASK] Update to `typo3/testing-framework` version 8.x**
`typo3/testing-framework` supports testing against two
TYPO3 versions per TF version and the current used 7.x
supports only TYPO3 v11 and v12.
After TYPO3 v11 support has been dropped, this change
upgrades the development dependency to the next version
and bolldozes the towards adding TYPO3 v13 as second
supported TYPO3 version.
```shell
composer require --dev \
"typo3/testing-framework":"^8.2.7"
```
- **[TASK] Use better suiting typing in `SiteBasedTestTrait`**
The `SiteBasedTestTrait` uses `AbstractInstruction` to declare
native types for method arguments and return types and PHPStan
complains about this because `typo3/testing-framework` methods
uses the `InstructionInterface` instead.
This change adopts …

[TASK] Upgrade to typo3/testing-framework 8.x

---

composer.json
packages/contribution/Classes/Command/DdevGenerateCommand.php
packages/contribution/Classes/Service/SiteStateService.php
packages/contribution/Configuration/Services.yaml
packages/contribution/composer.json
packages/contribution/ext_emconf.php

- **[TASK] Introduce local patch `contribution` package/extension**
To make contribution and workin on `EXT:deepltranslate_core` easier,
the provided ddev based local environment should be improved with
the ability to setup a basic working environment easily.
This change introduces a local development extension `EXT:contribution`
as preparation to give at least a simple and easy setup of a running
TYPO3 instance based on the TYPO3 `EXT:styleguide` core extension to
generate a backend and frontend tree / data. Combined with the TYPO3
v12 setup command this allows a simple instance generation.
For the start, the contribution extension only provide a cli command
to manage site root visibilities (on/off) having `EXT:styleguide`
generated trees in mind.
- **[TASK] Add `EXT:styleguide` and …

[TASK] Improve local ddev setup handling - first round

---

Build/phpstan/Core12/phpstan-baseline.neon
Classes/Domain/Repository/GlossaryRepository.php
Classes/Domain/Repository/PageTreeRepository.php
Classes/Hooks/Glossary/UpdatedGlossaryEntryTermHook.php

Doctrine DBAL 3.x renamed one exception class as a
breaking change and this change replaces occurances
to respect this.
```shell
Build/Scripts/runTests.sh -t 12 -p 8.1 -s phpstanGenerateBaseline
```
[1] https://github.com/doctrine/dbal/blob/3.9.3/UPGRADE.md#bc-break-doctrinedbaldbalexception-class-renamed

[TASK] Mitigate renamed doctrine exception class

---

.ddev/docker-compose.deeplmockserver.yml

docker-compose made the `version` option in the `docker-compose.yml`
syntax obsolete and throws notices. As docker is usualy kept up2date
and these version are out already a long time we can remove that
option to avoid the following notice on ddev start:
```
time="2024-12-12T14:26:54+01:00"
level=warning
msg="/var/www/work/webvision/wv_deepltranslate/.ddev/docker-compose.deeplmockserver.yml:
the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
```

[TASK] Avoid obsolete `version` in `.ddev/docker-compose.deeplmockserver.yml`

---

Classes/ViewHelpers/DeeplTranslateViewHelper.php

TYPO3 v12.2 deprecated the `SiteLanguage->getTwoLetterCode()` method
in favour of `SiteLanguage->getLocale()->getLanguageCode()`.
This change migrates all occurances throughout the code base as an
investment into the future.
[1] https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.3/Deprecation-99905-SiteLanguageIso-639-1Setting.html#deprecation-99905-site-language-iso-639-1-setting
[2] https://forge.typo3.org/issues/99905
[3] https://review.typo3.org/c/Packages/TYPO3.CMS/+/77597

[TASK] Avoid using deprecated `SiteLanguage->getTwoLetterCode()`

---

Build/phpstan/Core11/phpstan-baseline.neon
Build/phpstan/Core11/phpstan.neon
Build/phpstan/Core12/phpstan-baseline.neon
Build/phpstan/Core12/phpstan.neon
Classes/Event/Listener/RenderTranslatedFlagInFrontendPreviewMode.php
Configuration/Services.php
ext_localconf.php

TYPO3 v12 removed the `contentPostProc-all` aling with other hooks
in favour of new PSR-14 `AfterCacheableContentIsGeneratedEvent`.
The `DeeplPreviewFlagGeneratePageHook` is not called in TYPO3 v12
anymore and the translated preview flag is not displayed. Changed
behavour between TYPO3 v11 and v12 was not intented and simply an
oversight to mitigate when adding TYPO3 v12 support. Sadly, this
has not been detected for quite a while now.
This change introduces a event listener for the TYPO3 v12 event,
rendering the same flag to restore the missing and wanted preview
flag while keeping the hook implementation for TYPO3 v11 instances.
Choosen strategy follows the recommended way to migrate from the
hook to the event when dual TYPO3 version support is required.
```base …
```

[BUGFIX] Ender preview translated flag information in TYPO3 v12

---

Build/phpstan/Core12/phpstan-baseline.neon
Build/phpstan/Core12/phpstan.neon
Classes/Event/Listener/RenderTranslatedFlagInFrontendPreviewMode.php
Configuration/Services.php
ext_localconf.php

TYPO3 v12 removed the `contentPostProc-all` aling with other hooks
in favour of new PSR-14 `AfterCacheableContentIsGeneratedEvent`.
The `DeeplPreviewFlagGeneratePageHook` is not called in TYPO3 v12
anymore and the translated preview flag is not displayed. Changed
behavour between TYPO3 v11 and v12 was not intented and simply an
oversight to mitigate when adding TYPO3 v12 support. Sadly, this
has not been detected for quite a while now.
This change introduces a event listener for the TYPO3 v12 event,
rendering the same flag to restore the missing and wanted preview
flag while keeping the hook implementation for TYPO3 v11 instances.
Choosen strategy follows the recommended way to migrate from the
hook to the event when dual TYPO3 version support is required.
```base …
```

[BUGFIX] Ender preview translated flag information in TYPO3 v12 (5.x)

---

Build/phpstan/Core12/phpstan-baseline.neon
Build/phpstan/Core12/phpstan.neon
Build/phpunit/FunctionalTestsBootstrap.php
Tests/Functional/Fixtures/Extensions/testing_framework_backenduserhandler_replacement/Classes/Middleware/BackendUserHandler.php
Tests/Functional/Fixtures/Extensions/testing_framework_backenduserhandler_replacement/Configuration/RequestMiddlewares.php
Tests/Functional/Fixtures/Extensions/testing_framework_backenduserhandler_replacement/Configuration/Services.yaml
Tests/Functional/Fixtures/Extensions/testing_framework_backenduserhandler_replacement/composer.json
Tests/Functional/Fixtures/Extensions/testing_framework_backenduserhandler_replacement/ext_emconf.php
Tests/Functional/Regression/Fixtures/PreviewTranslationInformation.csv
Tests/Functional/Regression/Fixtures/PreviewTranslationInformation.typoscript
Tests/Functional/Regression/PreviewTranslationInformationTest.php
composer.json

Issue #395 has been recently fixed for 4.x and 5.x
with following pull-requests:
* https://github.com/web-vision/deepltranslate-core/pull/397
* https://github.com/web-vision/deepltranslate-core/pull/398
Adding regression test has been omited due to issues within the
`typo3/testing-framework` already. The major missing part boils
down to an incomplete frontend backend user authentication setup,
reported by Daniel Siepmann [1] and provided a pull-request [2].
* [1] Issue: https://github.com/TYPO3/testing-framework/pull/535
* [2] Pull-request: https://github.com/TYPO3/testing-framework/pull/536
The pull-request has been adopted by providing a test-fixture
extension replacing the BackendUserHandler with a fixed version.
Sadly, this required an additional temporary workaround within
the …

[TASK] Add regression test for issue #395

---

composer.json

The `typo3/cms-styleguide` package does not have requires towards
concrete TYPO3 system extension(s), which leads to side-effects
when trying to have multiple version for multi-core composer.json's
and let composer installalling suitable styleguide version for core
version.
The `sbuerk/typo3-cms-styleguide-version-sync` package has been
created as meta package to mitigate this issues acting as version
bridge.
As preparation for adding TYPO3 v13 support requiring dual versions,
we add it now for v12 only as a starting point and are forced to
update it when adding v13 support along the way.
```bash
composer require --dev \
"sbuerk/typo3-cms-styleguide-version-sync":"^12"
```

[TASK] Add `sbuerk/typo3-cms-styleguide-version-sync` development dependency

---

composer.json

This change adds the `typo3/cms-styleguide` extension as a new development
dependency to allow setting up a content tree within the local development
instance using ddev.
The styleguide package does not contain core system extension dependency
configuration and composer would therefore install the highest version,
even if not compatible when lower TYPO3 core version is used.
To mitigate this issue, the `sbuerk/typo3-styleguide-selector` is also
added to help composer selecting the correct version based on the real
TYPO3 version installed.
```bash
composer require --dev --no-update \
"typo3/cms-styleguide":"^11 || ^12" \
"sbuerk/typo3-styleguide-selector":"^11.5.5 || ^12.0.5"
```

[TASK] Add `typo3/cms-styleguide` along with version selector meta package

---

Configuration/Services.php

As other services can use the DeeplService and translate by their own, it's necessary to be able to override the ProcessingInstruction setting DeepL mode to true. As this is not the default and inside the core extension only needed for the command map, the service has to be made public, allowing external services adjusting the instructions.

[TASK] Make ProcessingInstructions public service for 4.x

---

Classes/Widgets/UsageWidget.php
Configuration/Services.php
Resources/Private/Backend/Templates/Widget/UsageWidget.html

TYPO3 v12 introduced a simplified ext:backend ModuleTemplate API [1]
to avoid the use of `StandaloneView` in the backend context and it's
not a suprise that TYPO3 v13 continued on this path and deprecated
it in TYPO3 13.3 [2] finally removing it as breaking change in TYPO3
v14 [3].
Sounding quite challenging, it's quite easy to make the `UsageWidget`
for `EXT:dashboard` compatible with TYPO3 v12 and v13 using simplified
backend module template API directly with the template override [4]
feature already included.
The surrounding `<p>` tag in the fluid template for the usage text
is replaced with `<span>` to make the UX feeling more user-friendly.
[1] https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-96730-SimplifiedExtbackendModuleTemplateAPI.html
[2] …

[TASK] Use simplified backend module template for `UsageWidget`

---

Classes/Hooks/AbstractTranslateHook.php
Classes/Hooks/TranslateHook.php

Since TYPO3 v12 the flash message severity are deprecated in favour of
the `ContextualFeedbackSeverity` and will fail in TYPO3 v13.
This change mitigates the deprecation and removal by directly using the
native PHP Enum for TYPO3 v12 and TYPO3 v13 by:
* Changing signature of `AbstractTranslateHook::flashMessages()` from
integer to `ContextualFeedbackSeverity`.
* Replace integer `-1` with `ContextualFeedbackSeverity::INFO` in two
places within `TranslateHook`. Something addon extensions needs to
handle on their own.
[1] https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-97787-SeveritiesOfFlashMessagesAndReportsDeprecated.html

[!!!][TASK] Mitigate depecated flash message severity

---

Build/Scripts/composer-for-core-version.sh
Build/phpstan/Core12/phpstan-baseline.neon
Build/phpstan/Core13/phpstan-baseline.neon
Classes/Event/Listener/RenderTranslatedFlagInFrontendPreviewMode.php
Classes/Upgrades/FormalityUpgradeWizard.php
Tests/Functional/AbstractDeepLTestCase.php
Tests/Functional/Fixtures/Traits/SiteBasedTestTrait.php
Tests/Functional/Hooks/TranslateHookTest.php
Tests/Functional/ViewHelpers/ExtensionActiveViewHelperTest.php

- **[TASK] Add `typo3/cms-install` as `$coreExtensionToLoad`**
Since TYPO3 v13 the `typo3/cms-install` extension is optional
and typo3/testing-framework no longer defines it as extension
to load (core) in functional tests.
`web-vision/deepltranslate-core` requires it for now to ensure
that upgrade wizards can be executed - an oversight from TYPO3
core team.
- **[TASK] Add dual TYPO3 version support for `SiteBasedTestTrait`**
The `SiteBasedTestTrait` takes care to write site configuration
in functional tests and TYPO3 v13 changed the logic of writing
it. Due to changed structure and the additional SiteSettings
support functional tests failing now with TYPO3 v13.
This change adopts required changed for the SiteBasedTestTrait
while keeping TYPO3 v12 support intact.
- **[TASK] Use suitable …

[TASK] Make functional tests executable for both core versions

---

Classes/Hooks/AbstractTranslateHook.php
Classes/Override/LocalizationController.php
Classes/Utility/DeeplBackendUtility.php
Tests/Functional/Hooks/TranslateHookTest.php
Tests/Functional/Regression/LocalizationInlineRegressionTest.php

Until now the DataHandler command map array has been misused
to transport custom `localize` command options relevant for
translation with DeepL, processed with a hook implementation
and using the original command.
TYPO3 v13 hardens the DataHandler even further, which is a
really good thing, and breaking fingers of developers mess
with the data monster - and loosing [1].
This change switch to a custom DataHandler command and using
the hook to handle the command directly by using the public
`DataHandler->localize()` method to mitigate the TYPO3 v13
exception thrown by `DataHandler->start()`.
Tests and link creation are aligned to use the new command
name and omit abitary and invalid options.
[1] https://review.typo3.org/c/Packages/TYPO3.CMS/+/83073

[TASK] Use custom DataHandler command instead of invalid cmdMap

---

.github/workflows/testcore13.yml
Build/phpstan/Core13/phpstan-baseline.neon

Functional tests and PHPStan code analysis has been
temporarly disabled against the TYPO3 v13 core, but
issues has been resolved meanwhile.
Enable jobs for TYPO3 v13 again. TYPO3 v13 phpstan
baseline updates, has been missed before due to
disabled pipelines.
```bash
Build/Scripts/runTests.sh -t 13 -p 8.2 -s composerUpdate
Build/Scripts/runTests.sh -t 13 -p 8.2 -s phpstanGenerateBaseline
```

[TASK] Enable temporarly disabled GitHub Action checks

---

.github/workflows/testcore12.yml
.github/workflows/testcore13.yml
composer.json

This change updates the version of the used
third party dependency to support PHP8.4 out
of the box and align with TYPO3 v12 and v13
support.
Tests are now also executed with PHP 8.4.
```shell
composer require --no-update \
"deeplcom/deepl-php":"^1.10.1"
```

[TASK] Update `deeplcom/deepl-php:^1.10.1`

---

README.md

Updated the README to include a new "Add-Ons" section highlighting the DeepL Translate Glossary. Removed specific sponsor details for the glossary feature to streamline content.

[TASK] Add glossary add-on section to README

---

Tests/Functional/AbstractDeepLTestCase.php
Tests/Functional/ViewHelpers/ExtensionActiveViewHelperTest.php
composer.json
ext_emconf.php

Adjust updates on required dependencies to deepltranslate-core after extracting glossary to an on add-on extension
* `typo3/cms-scheduler` is not mandantory for the core extension and is removed. Dependency (soft) of extracted `web-vision/deepltranslate-glossary`
* `typo3/cms-install` is optional since TYPO3 v13 and is removed as hard dependency. Readded as development dependy for functional tests. Added as suggestion as otherwise upgrade wizards are not executable which makes updates nearly impossible.

[TASK] Redefine composer dependencies

---

ext_emconf.php

For classic mode instances, the system ships self-installed packages
for `DeepL` and `Http\Discovery\`.
As composer-based installations ignore autoloading in `ext_emconf.php`,
this can be safely added to ensure external dependencies installed during
release will work out of the box.

[TASK]  Define classic mode autoloader in `ext_emconf.php` for depending and shipped packages

---

Classes/Event/Listener/RenderLocalizationSelect.php

This error occurs directly after opening the backend when the page module is the default module: https://example.org/typo3/module/web/

[BUGFIX] Avoid PHP warning when query parameter "id" is missing

---

Classes/Form/TranslationDropdownGenerator.php
Resources/Private/Backend/Partials/AdditionalTranslation/DeeplDefault.html

Fixes #428
I am not completely happy with the `f:replace` solution. But it worked for me. Feel free to consider this as a draft and create a more beautiful solution. 🙂

[BUGFIX] Make custom DataHandler command in select boxes work

---

Classes/Form/TranslationDropdownGenerator.php
Classes/ViewHelpers/DeeplTranslateViewHelper.php
Resources/Private/Backend/Partials/AdditionalTranslation/DeeplDefault.html

Recently merged pull-request #429 to solve page
settings translation provided two changes which
fixes the same issue in two different ways by
providing the correct DataHandler command name
in the url.
Only one is needed and allows to drop the not
so nice `f:replace()` ViewHelper usage within
the partial and keeping the working state.
Replace ViewHelper is now removed again and
minor code cleanup (outcommented code) done
in the same step.
Related: #429 (#428) da13ab1cae106bd70892a2db9587d89af8d912a7

[TASK] Remove obsolete f:replace from partial

---

Build/phpstan/Core12/classAliasses.php
Build/phpstan/Core12/phpstan-baseline.neon
Build/phpstan/Core12/phpstan.neon
Build/phpstan/Core13/classAliasses.php
Build/phpstan/Core13/phpstan-baseline.neon
Build/phpstan/Core13/phpstan.neon
Classes/Override/Core12/DatabaseRecordList.php
Classes/Override/Core12/DatabaseRecordListCore.php
Classes/Override/Core12/DatabaseRecordListWithGridelements.php
composer.json
ext_emconf.php
ext_localconf.php

With `gridelements` installed the extension internal override of the
DatabaseRecordList won't work anymore, as `gridelements` overrides the
same way.
This commit adjusts the implementation by overriding the respective
class depending on the installed `gridelements` extension and respecting
the setting if the nested content element support is enabled.
As `gridelements` has no public available repository for TYPO3 13,
assume this workflow works in 13.

[BUGFIX] Add support for nested `EXT:gridelements`

---

.github/workflows/publish.yml

This change streamlines the publish GitHub
workflow slightly adopting latest changes
in other projects.
* Only add GitHub release body prepanding based
git tag when more than one line.
* Only push the github release link as tailor
upload comment.

[TASK] Minor streamlining of publish workflow

---

.github/workflows/publish.yml

With recent change on the publis workflow the
extension key detection has been accedently
dropped.
This change reintroduces the detection.

[TASK] Adding extension key detection again

---

.github/workflows/publish.yml
composer.json

Private addons has been developed further, and in
preparation to adopt `5.x` along with package and
extension_key renaming rised from `0.x` to `1.x`
for `4.x` version of this package. To mitigate
unsupported installation matrix, the old `0.x`
development versions are now added as conflict:
```shell
cat <<< $(
jq '.conflict."web-vision/deepltranslate-assets" = "<1.0.0 >=2.0.0"' \
composer.json | \
jq '.conflict."web-vision/deepltranslate-auto-renew" = "<1.0.0 >=2.0.0"' | \
jq '.conflict."web-vision/deepltranslate-mass" = "<1.0.0 >=2.0.0"'
) > composer.json
```

[TASK] Add unsupported private addon versions as conflict

---

.github/workflows/publish.yml
composer.json

Update deepl library to include PHP 8.4 related fixes,
minimum version is required to ship compatible version
with TYPO3 Extension Repository (TER) release.
```shell
BIN_COMPOSER="$( which composer )" \
&& ${BIN_COMPOSER} require --no-update \
'deeplcom/deepl-php':'^1.11.1'
```

[TASK] Update `deeplcom/deepl-php`

---

composer.json
ext_emconf.php

This change syncronizes dependency defintions between
`ext_emconf.php` (classic mode / functional tests) and
`composer.json` (composer mode).
```shell
BIN_COMPOSER="$( which composer )" \
&& ${BIN_COMPOSER} config license "GPL-2.0-or-later"
```

[TASK] Syncronize `ext_emconf.php` and `composer.json`

---

.github/workflows/publish.yml

Use correct github repository name and
remove unused environment variable in
workflow `publish`.

[TASK] Minor cleanup of `publish` workflow

---

composer.json

Recently, concflict definition for private addon extensions
has been added to allow only the `1.x` range of them, sadly
a not workable constraint has been used.
Used invalid constraint:
```
<1.0.0 >=2.0.0"
```
tells composer that a given version must be lesser than
`1.0.0` and greater-or-equal than `2.0.0` at the same
time, which is not possible. The correct way would be to
rephase this to an `< 1.0.0 OR >= 2.0.0 are conflicting`
and reflected by the now set constraint:
```
<1.0.0 || >=2.0.0"
```
```shell
cat <<< $(
jq '.conflict."web-vision/deepltranslate-assets" = "<1.0.0 || >=2.0.0"' \
composer.json | \
jq '.conflict."web-vision/deepltranslate-auto-renew" = "<1.0.0 || >=2.0.0"' | \
jq '.conflict."web-vision/deepltranslate-mass" = "<1.0.0 || >=2.0.0"'
) > composer.json …
```

[TASK] Use correct multi-version conflict constraints

---

CHANGELOG.md
Documentation/Administration/Updates/Index.rst

Update to 5.0 was possible, but then I had to migrate the extension settings,
which showed that the package key was changed as well.
I added a note about this into the Changelog, since this is a rather large alteration.

[DOCS] Mention package renaming and 5.x upgrade hurdles

---

Build/phpstan/Core12/phpstan-baseline.neon
Build/phpstan/Core13/phpstan-baseline.neon
Classes/Exception/LanguageIsoCodeNotFoundException.php
Classes/Hooks/AbstractTranslateHook.php
Classes/Service/LanguageService.php
Classes/Utility/DeeplBackendUtility.php
Tests/Functional/Services/LanguageServiceTest.php
UPGRADE.md

DeeplTranslate only supports a narrowed down list of selected
languages, which is only a subset of TYPO3 supported languages
and the reason why a dedicated option `DeeplTranslate Language`
is provided on the SiteConfig language level.
As a left over from the original `Proof-of-Concept` phase and
the first version iteration a fallback to SiteConfig language
`HREF` and `ISO Locale` has been in place trying to get some
kind of fallback. That turned out not to be that reliable and
becomes more unreliable and invalid with planned upcoming
features.
Even with the fallback in place it has been recommended to
specify the deepl translate language manually for a long time
and the fallback is now removed in favour of explicit, manual
configuration.
> [!IMPORTANT]
> This is technically breaking and …

[!!!][TASK] Remove `DeepL Translate` fallback to `HREF` and `ISO` config

---

Classes/Configuration.php

It's a good practice to define interfaces and provide a default
implementation making xclass strategies, stubbing or mocking in
tests and similar techniques easier. Default implementation, if
provided, should be configured in the DI configuration as alias
for the interface, not done for the `ConfigurationInterface` on
the default implementation `Configuration`.
TYPO3 `SingeltonInterface` stems from old times before DI has
been introduced to TYPO3 and has been used to mark classes as
`shared` (only instanciated onces) within `GeneralUtilitiy`,
something is the default behaviour for services in DI as long
as not configured otherwise. Having `ConfigurationInterface`
and `Configuration` DI aware makes the `SingeltonInterface`
obsolete.
Services implementing `SingletonInterface` are …

[TASK] Make `Configuration` default for `ConfigurationInterface`

---

Classes/Override/CommandMapPostProcessingHook.php

The `b13/container` extension (`EXT:container` ) implements a custom
DataHandler hook to process data in the required manner and recently
splitted the method `localizeOrCopyToLanguage()` into two dedicated
methods for the `CommandMapPostProcessingHook` [2] to fix an issue [1].
`EXT:deepltranslate_core` needs to override that hook in case that
extension is installed to ensure both extension to work and broke
due to that change.
This change mitigates this by verify the existance of the methods
now and call the existing once and throws an exception if if will
be renamed again in the future.
[1] https://github.com/b13/container/issues/609
[2] https://github.com/b13/container/pull/617

[BUGFIX] Mitigate splitted DataHandler hook method of `EXT:container`

---

.gitignore
Build/Scripts/runTests.sh

This change makes it possible to have `deepl-base` symlinked
within the `packages` folder and `Build/Scripts/runTests.sh`
mounting the volumn using full path locally and in containers.
That allows using deepl-base from checkout repository within
the private monorepository like setup without needing to have
changes pushed to github (locally).

[TASK] Make it possible to have deepl-base symlinked in `packages/`

---

.github/workflows/publish.yml
Tests/Functional/AbstractDeepLTestCase.php
Tests/Functional/Container/ContentElementsInContainerTest.php
Tests/Functional/Hooks/TranslationWithModifiedTcaConfigurationTest.php
Tests/Functional/Regression/LocalizationInlineRegressionTest.php
composer.json
ext_emconf.php

Direct PHP API Client package dependency is now replaced with
the indirect dependency using `web-vision/deeplcom-deepl-php`
as shared extension allowing to have more then one extension
released in TER requiring that dependency and bundling client
package for TER uploade is removed along the way.
```shell
BIN_COMPOSER="$(which composer)" && \
${BIN_COMPOSER} remove --no-update \
'deeplcom/deepl-php' && \
${BIN_COMPOSER} require --no-update \
'web-vision/deeplcom-deepl-php':'^1.12.0'
```

[TASK] Switch to indirect `web-vision/deeplcom-deepl-php` client extension

---

ext_emconf.php

Since TYPO3 v12 it should be obsolete to state in the
`ext_emconf.php` file when extension composer.json has
such a section and should not be merged.
That has not been verified to the very end and we
restore the autoload section in `ext_emconf.php`
for now.

[TASK] Restore `ext_emconf.php` autoload namespace registration

---

Classes/Event/Listener/ApplyLocalizationModesEventListener.php
composer.json
ext_emconf.php

- **[TASK] Adopt changed core translation mode identifiers**
The identifier used for core translation modes in the
dependency package `web-vision/deepl-base` has been
fixed with [1] and released as `1.0.2` [2] to restore
working TYPO3 core localization and copy behaviour.
This change uses the same identifier with the class
constants from the LocalizationController for own
custom localization modes as `after` definition to
keep the same sorting alive we strives for and acts
as preparation for rising the dependency to `1.0.2`
as minimal version to ensure overall working state.
[1] https://github.com/web-vision/deepl-base/pull/13
[2] https://github.com/web-vision/deepl-base/releases/tag/1.0.2
- **[TASK] Raise `web-vision/deepl-base` to `^1.0.2`**
External dependency package …

[TASK] Raise `web-vision/deepl-base` to include latest bugfix
