web-vision/deepltranslate-core

ext_conf_template.txt

Changed api version.
See https://www.deepl.com/en/docs-api.html?part=accessing

[TASK] Changed api version

---

Classes/Override/LocalizationController.php

Ensures compatibility with TYPO3 10LTS

Add missing parameters for getPageColumns call

---

ext_conf_template.txt

[TASK] Add note for deepl free endpoint

---

Classes/Service/DeeplService.php

- Resolves: Issue #23 & Issue #11

[TASK] Fix list of supported languages

---

Classes/Controller/SettingsController.php
Classes/Service/DeeplService.php
Classes/Service/GoogleTranslateService.php
ext_conf_template.txt
ext_emconf.php
ext_tables.php

- Regarding https://github.com/web-vision/wv_deepltranslate/issues/35
- Fixed https://github.com/b13/container/issues/188

Fixed TYPO3 v11 compatibility

---

Classes/Service/DeeplService.php
ext_conf_template.txt

[FEATURE] Add formality support for deepl

---

Configuration/TCA/tx_deepl_settings.php

[BUGFIX] Misconfigured label in TCA

---

Classes/Override/LocalizationController.php

[BUGFIX] localization wizard with EXT:container

---

Classes/Command/GlossariesEntriesListCommand.php
Classes/Domain/Repository/SettingsRepository.php
Classes/Hooks/ButtonBarHook.php
Classes/Hooks/DataHandlerHook.php
Classes/Hooks/TranslateHook.php
Classes/Service/Client/Client.php
Classes/Service/DeeplService.php

There is a cgl:fix in composer.json but this requires changes.
Run
` composer cs:check`
To ensure a permanent solution, GitHub CI workflows should be added to run this regularly
Related: #102

[TASK] Run CGL fix

---

Classes/Service/DeeplService.php

[BUGFIX] Fix exception due to missing use statement

---

Classes/Hooks/TranslateHook.php
Classes/Utility/HtmlUtility.php

Move Utility function in separated class

Move html utility function

---

.ddev/commands/web/update-to-v10
.ddev/commands/web/update-to-v11
.ddev/commands/web/update-to-v9
Classes/Controller/SettingsController.php
Classes/Hooks/TranslateHook.php
Classes/Service/DeeplService.php
Classes/Utility/HtmlUtility.php
Tests/Functional/Hooks/TranslateHookTest.php
Tests/Functional/Services/DeeplServiceTest.php
composer.json

Translation Check/Flag for Page Properties

---

Classes/Hooks/AllowLanguageSynchronizationHook.php
Classes/Service/DeeplService.php
Resources/Private/Backend/Partials/PageLayout/LanguageColumns.html
Resources/Private/Backend/Partials/v10/PageLayout/LanguageColumns.html

fixes #153 
fixes #152 
fixes #150

Fix errors/warnings with PHP 8.1

---

Classes/Hooks/ButtonBarHook.php
Classes/TCA/LanguageSelectorItemsProc.php

I just tried the latest master, because I was curious how the refactored glossary feature is doing* and found two problems while clicking around in my backend.
*btw: Much better than before - And even working! :smile:

Improve variable types

---

Classes/Hooks/TranslateHook.php

[TASK] Remove stripTag function in translateHook

---

Documentation/Introduction/Sponsoring/Index.rst
README.md

[TASK] Add sponsor to Documentation

---

Classes/Override/LocalizationController.php

[BUGFIX] Fix choose language step skip

---

Classes/Override/LocalizationController.php

[BUGFIX] Fix missing configuration object for localization wizard

---

Classes/Service/DeeplService.php
Classes/Service/LanguageService.php
Tests/Functional/Services/DeeplServiceTest.php
Tests/Functional/Services/LanguageServiceTest.php

When source language not supported give a fallback to auto-detect. Is only supported for sources language

[TASK] Add auto detect source language

---

Classes/Hooks/AllowLanguageSynchronizationHook.php
Classes/Service/DeeplService.php

fix #239 Access to undefined array keys in list view

---

Configuration/Icons.php
ext_localconf.php

[TASK] Move Icon registry to Configuration/Icons.php

---

Classes/Configuration.php
Classes/Domain/Repository/GlossaryEntryRepository.php
Classes/Domain/Repository/GlossaryRepository.php
Classes/Hooks/AllowLanguageSynchronizationHook.php
Classes/Service/DeeplGlossaryService.php
Classes/Service/DeeplService.php
Classes/Service/LanguageService.php
Classes/Utility/DeeplBackendUtility.php
Classes/Utility/HtmlUtility.php
Classes/ViewHelpers/DeeplTranslateViewHelper.php

This change adds a couple of `@todo` and
comments to several places to emphasises
where further thinking needs to be done.
Releases: main

[TASK] Add some `todo` markers and comments

---

Classes/Utility/DeeplBackendUtility.php

[BUGFIX] Detected current page right for pages

---

Classes/Service/DeeplService.php

Just a rough idea....
Resolves: #305

FIX: page module dead in offline mode

---

Classes/Widgets/UsageWidget.php
Configuration/Backend/DashboardWidgetGroups.php
Configuration/Services.php
Resources/Private/Backend/Templates/Widget/UsageWidget.html
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf
composer.json

This widget shows the current character limit of the DeeoL Translate function, as a TYPO3 dashboard widget.

[TASK] Create deepl usage widget

---

CHANGELOG.md
ext_emconf.php

* Translation access configurable by group
* Formality is now configurable by language and site
Please use the UpgradeWizard fixing the language formality from the old to the new structure.
* DeepL client respects TYPO3 proxy settings full
* Glossary used without request needed

[TASK] Release 4.4.0

---

Build/phpstan/Core11/phpstan-baseline.neon
Build/phpstan/Core12/phpstan-baseline.neon
ext_emconf.php

This is only a TER bugfix release, Fixes the vendor folder and adds external dependencies for classic installations
Fixes #425

[TASK] Prepare release

---

Resources/Public/Icons/Extension.svg

Update descriptions and extension names for clearer use cases.
Update the Extension Icon

[TASK] Streamline Extension icons and descriptions
